Login
H6-Handvaerkervognen/API pull request #3
Opened 2023-04-25 11:41 UTC by NansyT

2023-04-25 12:30 UTC, WizzyVeigar requested changes
Overall good but small edits needed

2023-04-25 12:30 UTC, WizzyVeigar commented on HåndværkervognenAPI/HåndværkervognenAPI/Controllers/AppController.cs
> +using HåndværkervognenAPI.Model;
Model namespace skal fjernes og ændres til Models alle steder

2023-04-25 12:30 UTC, WizzyVeigar commented on HåndværkervognenAPI/HåndværkervognenAPI/Controllers/LoginController.cs
> +            loginService.AuthorizeLogin(loginCredentials);
Lav en if for at se om Authorize er true

2023-04-25 12:30 UTC, WizzyVeigar commented on HåndværkervognenAPI/HåndværkervognenAPI/Controllers/LoginController.cs
> +        loginService.RegisterUser(loginCredentials);
Få response om register gik igennem

2023-04-25 12:30 UTC, WizzyVeigar commented on HåndværkervognenAPI/HåndværkervognenAPI/Database/DataManager.cs
> +﻿using HåndværkervognenAPI.Model;
Fjern Model namespace

2023-04-25 12:30 UTC, WizzyVeigar commented on HåndværkervognenAPI/HåndværkervognenAPI/Database/DataManager.cs
>          public List<AlarmDal> GetAlarms(string appId)
Overvej factory pattern så Datamanager ikke opretter modeller.

2023-04-25 12:30 UTC, WizzyVeigar commented on HåndværkervognenAPI/HåndværkervognenAPI/Database/DataManager.cs
> +using HåndværkervognenAPI.Models;
Vi skal nok have noget try catch et sted.

2023-04-25 12:30 UTC, WizzyVeigar commented on HåndværkervognenAPI/HåndværkervognenAPI/Database/DataManager.cs
> +using System.Data.SqlClient;
Giv response på command status

2023-04-25 12:30 UTC, WizzyVeigar commented on HåndværkervognenAPI/HåndværkervognenAPI/Database/IDatabase.cs
> +﻿using HåndværkervognenAPI.Model;
Fjern Model

2023-04-25 12:30 UTC, WizzyVeigar commented on HåndværkervognenAPI/HåndværkervognenAPI/Managers/AppManager.cs
>  using HåndværkervognenAPI.Model;
Fjern Model.

2023-04-25 12:30 UTC, WizzyVeigar commented on HåndværkervognenAPI/HåndværkervognenAPI/Managers/AppManager.cs
> +        public bool StopAlarm(string AlarmId)
AlarmId med stort

2023-04-25 12:30 UTC, WizzyVeigar commented on HåndværkervognenAPI/HåndværkervognenAPI/Managers/AppManager.cs
> +        public bool UpdateTimeSpan(string AppId, AlarmInfoDto alarmInfo)
AlarmInfoDto med stort

2023-04-25 12:30 UTC, WizzyVeigar commented on HåndværkervognenAPI/HåndværkervognenAPI/Managers/IAppService.cs
> +        bool UpdateTimeSpan(string AppId, AlarmInfoDto alarmInfo);
AppId med stort

2023-04-25 12:30 UTC, WizzyVeigar commented on HåndværkervognenAPI/HåndværkervognenAPI/Managers/IAppService.cs
> +        bool StopAlarm(string AlarmId);
AlarmId med stort

2023-04-25 12:30 UTC, WizzyVeigar commented on HåndværkervognenAPI/HåndværkervognenAPI/Managers/NotificationAlarmManager.cs
> +using HåndværkervognenAPI.Model;
Fjern Model

2023-04-25 12:30 UTC, WizzyVeigar commented on HåndværkervognenAPI/HåndværkervognenAPI/Managers/loginManager.cs
>      public class loginManager : ILoginService
loginManager med stort tak!

2023-04-25 12:30 UTC, WizzyVeigar commented on HåndværkervognenAPI/HåndværkervognenAPI/Managers/loginManager.cs
> +        private IDatabase database;
angiv _ til database og hashing

2023-04-25 12:30 UTC, WizzyVeigar commented on HåndværkervognenAPI/HåndværkervognenAPI/Managers/loginManager.cs
> +        public void RegisterUser(LoginCredentials loginCredentials)
Tilføj return type

2023-04-25 12:30 UTC, WizzyVeigar commented on HåndværkervognenAPI/HåndværkervognenAPI/Models/LoginCredentials.cs
> +﻿namespace HåndværkervognenAPI.Models
CTRL + K + D

2023-04-25 12:30 UTC, WizzyVeigar commented on HåndværkervognenAPI/HåndværkervognenAPI/Models/AlarmInfoDto.cs
CTRL + K + D

2023-04-25 12:30 UTC, WizzyVeigar commented on HåndværkervognenAPI/HåndværkervognenAPI/Models/PairInfo.cs
CTRL + K + D

2023-04-25 12:30 UTC, WizzyVeigar commented on HåndværkervognenAPI/HåndværkervognenAPI/Models/PairInfo.cs
> +        public string AppId { get; private set; }
AppId skal ændres til username

2023-04-25 12:31 UTC, NansyT commented on HåndværkervognenAPI/HåndværkervognenAPI/Managers/AppManager.cs
> +        public bool UpdateTimeSpan(string AppId, AlarmInfoDto alarmInfo)
No, AppId med stort

2023-04-26 07:51 UTC, WizzyVeigar approved these changes
LG2M!

2023-04-26 07:53 UTC, merged